### ISSUE TITLE
Why not just use Jekyll?

### ISSUE THREAD

**Issue by kidwm** [twunbound/twunbound.github.io#4]
since GitHub Pages support Jekyll static page generator.

**Comment by Rplus** [comment]
:+1:

**Comment by tony1223** [comment]
Because I didn't have time to set up the stack. lol 

Welcome to send a PR with Jekyll.

**Comment by wildskyf** [comment]
我來幫忙吧！

**Comment by tony1223** [comment]
thanks a lot !!
